spring:
  application:
    name: ms-student
  datasource:
    url: jdbc:mysql://localhost:3306/school?useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Puede ser "validate", "update", "create", "create-drop" según tus necesidades
    show-sql: true # Muestra las consultas SQL en la consola
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # Cambia según tu versión de MySQL
server:
  port: 9999
